<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- Sem wwwroot: evita DirectoryNotFoundException no bootstrap de Static Web Assets (.NET 8+) -->
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
    <RootNamespace>Simcag.IngestionService.Api</RootNamespace>
    <UserSecretsId>b161e203-22c5-41e6-b347-9bd8e66d785d</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
    <PackageReference Include="StackExchange.Redis" Version="2.7.33" />
    <PackageReference Include="Simcag.Shared" Version="1.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Simcag.IngestionService.Application\Simcag.IngestionService.Application.csproj" />
    <ProjectReference Include="..\Simcag.IngestionService.Infrastructure\Simcag.IngestionService.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Configuration\" />
    <Folder Include="Contracts\Requests\" />
    <Folder Include="Contracts\Responses\" />
    <Folder Include="Extensions\" />
    <Folder Include="Filters\" />
    <Folder Include="HealthChecks\" />
    <Folder Include="Middlewares\" />
  </ItemGroup>

</Project>