<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Simcag.Shared" Version="1.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference
			Include="..\Simcag.IngestionService.Domain\Simcag.IngestionService.Domain.csproj" />
		<ProjectReference
			Include="..\Simcag.IngestionService.Infrastructure\Simcag.IngestionService.Infrastructure.csproj" />
	</ItemGroup>

</Project>